// <auto-generated />
namespace Todo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Todos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Todos));
        
        string IMigrationMetadata.Id
        {
            get { return "202002130801559_Todos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
